### ISSUE TITLE
Shape Excavation not working

### ISSUE THREAD

**Issue by darkequine** [qyl27/DiggusMaximus#7]
I am on 1.21.5, Fabric version 1.7.5 of the mod. I have my Shape Excavation key sent to ` (tilde) and when I hit the button and click a block, nothing happens. The only block that breaks is the one I originally clicked. I am also using the Yeeterite Pickaxe from Brrrrrrock at the bedrock layer trying to mine in a 3x3 tunnel.

**Comment by qyl27** [comment]
It is strange, are you trying to break a bedrock?

**Comment by darkequine** [comment]
Yes, I am trying to break bedrock. I am standing on y -63 trying to use the 3x3 tunnel. Sometimes I'll click on the bedrock block other times I've clicked on deepslate, but the tunnel doesn't happen. It only breaks the first block clicked.

**Comment by qyl27** [comment]
Did it work when you breaking stones normally?

**Comment by darkequine** [comment]
No, nothing works. None of the keybinds do anything.

**Comment by qyl27** [comment]
Oh, would you like to provide your game log?

**Comment by darkequine** [comment]
[latest.log](https://github.com/user-attachments/files/21845911/latest.log)

**Comment by qyl27** [comment]
It looks everything ok, how about to provide the full mods pack? I must check it on my machine I think

**Comment by darkequine** [comment]
The mod works with other tools, just not Yeeterite. How would I send the modpack? It is not letting me upload a .zip file.

**Comment by qyl27** [comment]
> The mod works with other tools, just not Yeeterite. How would I send the modpack? It is not letting me upload a .zip file.

Use an online drive, and send a share link.

**Comment by darkequine** [comment]
Just the mods folder - https://drive.google.com/file/d/16MZNAEZ5WLxeyXShmWrQpijcgN8mwuwz/view?usp=drive_link
The full modpack - https://drive.google.com/file/d/1kRkqclNxFz8HpiIHE69q7rhAYe4euoCR/view?usp=drive_link

**Comment by qyl27** [comment]
I can't access it because lack of permission.

**Comment by darkequine** [comment]
Sorry about that. I updated the permissions.

**Comment by darkequine** [comment]
Fixed it by adding the Yeeterite Pickaxe to the allowed tools list. Interesting that native compatibility was lost in an update somewhere, but at least there is a workaround.

After closing the game and trying to launch again, it is now crashing.

[crash-2025-08-27_06.11.45-client.txt](https://github.com/user-attachments/files/22007268/crash-2025-08-27_06.11.45-client.txt)

**Comment by qyl27** [comment]
Oh, did any early versions of Diggus Maximus works?

**Comment by darkequine** [comment]
The last version that worked as intended was 1.7.1 for Java 1.21.4

**Comment by qyl27** [comment]
Thank you, I'll check it.

**Comment by qyl27** [comment]
I have published the fixed version 1.7.6

**Comment by darkequine** [comment]
It still doesn't work. I still can't veinmine at the bedrock level. Adding
a tool to the allowed list no longer makes the game crash though.

**Comment by qyl27** [comment]
Still not veinmining with the yeeterire pickaxe?

**Comment by qyl27** [comment]
Yeeterite is not open-source, so I can't figure out the cause. Would you like to report it to its authors?  
I'm happy to provide further information.

**Comment by darkequine** [comment]
I will report it to them. I will let them know to reach out to you for
follow up information.

**Comment by A5ho9999** [comment]
This can be closed, a fix on my end will be released shortly (it was just the breakable method being changed from a block to a blockstate)

**Comment by qyl27** [comment]
> This can be closed, a fix on my end will be released shortly (it was just the breakable method being changed from a block to a blockstate)

Ah, thanks a lot.
